### ISSUE TITLE
Syntax error in learn starter

### ISSUE THREAD

**Issue by adityan150** [vercel/next-learn#107]
I followed the official documentation for setting up next.js project.
**Project command:**
`npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
`
npm run dev gave the following error:

```
 aditya@acer:~/Dev/nextjs-blog$ npm run dev

> dev
> next dev

/home/aditya/Dev/nextjs-blog/node_modules/next/dist/cli/next-dev.js:316
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/aditya/Dev/nextjs-blog/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/aditya/Dev/nextjs-blog/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by adityan150** [comment]
I figured out that the problem was with old version of nodejs and updating it to the latest verion resolved the issue.
