### ISSUE TITLE
SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by cmrudi** [vercel/next-learn#120]
Run `npm run dev`

Then below error comeout

`SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/cutmeurahrudi/personal_project/nextjs/nextjs-blog/node_modules/next/dist/telemetry/post-payload.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-blog@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjs-blog@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cutmeurahrudi/.npm/_logs/2023-05-20T17_51_39_644Z-debug.log`

**Comment by shinena** [comment]
node version is too low

**Comment by cmrudi** [comment]
@shinena It works after upgrading. Thank youu
