### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by josephchan7939** [vercel/next-learn#123]
When I run "npm run dev",I get the following error,It seems that the node version is too old??but my os is win7,so i set up node v13.14.0 which is the last version can be set up on win7,so how can i deal with it, Any tips are appreciated! :

D:\nextjs\nextjs-blog\node_modules\next\dist\cli\next-dev.js:260
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.dev (D:\nextjs\nextjs-blog\node_modules\next\dist\lib\commands.js:15:30)
    at Object.<anonymous> (D:\nextjs\nextjs-blog\node_modules\next\dist\bin\next:150:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `next dev`
npm ERR! Exit status 1

**Comment by mistyrain-jiangnan** [comment]
> 

我的node 版本为14.19.3也出现了这个问题。切换成18.15.0 版本能正常的启动！

**Comment by appydam** [comment]
install the latest version of node.

I was learning nextjs of its documentation. I also faced this issue.

I resolved it by upgrading node to `v20.7.0`

**Comment by manovotny** [comment]
We have updated the documentation to state that Node 18 is the latest required version. Can you please try Node 18 and let us know if the issue persists?
