### ISSUE TITLE
Dev Mode > authenticate > signIn('credentials', Object.fromEntries(formData)) Throws Error: NEXT_REDIRECT 

### ISSUE THREAD

**Issue by robbmerritt** [vercel/next-learn#253]
Only in Dev, when I sign in with correct creds, a redirect error is thrown and the user does not get signed in.
This does not happen in prod.

My code appears to be the same as the final example.
https://github.com/robbmerritt/nextjs-dashboard
https://nextjs-dashboard-liart.vercel.app/login

Since it works in prod and not dev, It could be a race condition.

```
authenticate formData _FormData [FormData] {
  [Symbol(state)]: [
    { name: '$ACTION_REF_1', value: '' },
    {
      name: '$ACTION_1:0',
      value: '{"id":"0110ace4a8b5d7cd1928466d5e4b8d139b52cae0","bound":"$@1"}'
    },
    { name: '$ACTION_1:1', value: '["$undefined"]' },
    { name: '$ACTION_KEY', value: 'k305195570' },
    { name: 'email', value: 'user@nextmail.com' },
    { name: 'password', value: '123456' }
  ]
}
authenticate error Error: NEXT_REDIRECT
    at getRedirectError (webpack-internal:///(action-browser)/./node_modules/next/dist/client/components/redirect.js:44:19)
    at redirect (webpack-internal:///(action-browser)/./node_modules/next/dist/client/components/redirect.js:54:11)
    at signIn (webpack-internal:///(action-browser)/./node_modules/next-auth/lib/actions.js:63:89)
    at async authenticate (webpack-internal:///(action-browser)/./app/lib/actions.ts:127:9)
    at async /Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:479
    at async tK (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:37:4768)
    at async ri (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:28770)
    at async doRender (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:1340:26)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:1500:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:1408:28)
    at async DevServer.renderPageComponent (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:1760:24)
    at async DevServer.renderToResponseImpl (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:1798:32)
    at async DevServer.pipeImpl (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:851:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/next-server.js:266:17)
    at async DevServer.handleRequestImpl (/Users/robbmerritt/Workspace/nextjs-dashboard/node_modules/next/dist/server/base-server.js:748:17) {
  digest: 'NEXT_REDIRECT;replace;http://localhost:3000/login?page=2&callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Flogin%3Fpage%3D2;false',
  mutableCookies: p {
    _parsed: Map(2) {
      'next-auth.callback-url' => [Object],
      'next-auth.session-token' => [Object]
    },
    _headers: _HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

**Comment by robbmerritt** [comment]
Duplicate issue:
https://github.com/vercel/next-learn/issues/252
