### ISSUE TITLE
Command "npm run seed" fails

### ISSUE THREAD

**Issue by GwakoSyprose** [vercel/next-learn#372]
Nodejs version - v21.1.0
npm version - 10.2.0
OS - Ubuntu

I have followed the process and even created the database but when I run the "npm run seed" command. I get this error:
```
> seed
> node -r dotenv/config ./scripts/seed.js

node:events:493
      throw er; // Unhandled 'error' event
      ^

AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at internalConnectMultiple (node:net:1177:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/syprose/projects/learn/nextjs/nextjs-dashboard/node_modules/ws/lib/websocket.js:1016:13)
    at ClientRequest.<anonymous> (/home/syprose/projects/learn/nextjs/nextjs-dashboard/node_modules/ws/lib/websocket.js:864:5)
    at ClientRequest.emit (node:events:515:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:515:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 100.26.116.133:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '100.26.116.133',
      port: 443
    },
    Error: connect ENETUNREACH 64:ff9b::1717:e509:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '64:ff9b::1717:e509',
      port: 443
    },
    Error: connect ETIMEDOUT 44.199.59.172:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '44.199.59.172',
      port: 443
    },
    Error: connect ENETUNREACH 64:ff9b::2ccf:9495:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '64:ff9b::2ccf:9495',
      port: 443
    },
    Error: connect ETIMEDOUT 44.207.148.149:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '44.207.148.149',
      port: 443
    },
    Error: connect ENETUNREACH 64:ff9b::3414:6b83:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '64:ff9b::3414:6b83',
      port: 443
    },
    Error: connect ETIMEDOUT 34.194.100.28:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '34.194.100.28',
      port: 443
    },
    Error: connect ENETUNREACH 64:ff9b::2cc7:3bac:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '64:ff9b::2cc7:3bac',
      port: 443
    },
    Error: connect ETIMEDOUT 23.23.229.9:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '23.23.229.9',
      port: 443
    },
    Error: connect ENETUNREACH 64:ff9b::22c2:641c:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '64:ff9b::22c2:641c',
      port: 443
    },
    Error: connect ETIMEDOUT 52.20.107.131:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '52.20.107.131',
      port: 443
    },
    Error: connect ENETUNREACH 64:ff9b::641a:7485:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '64:ff9b::641a:7485',
      port: 443
    }
  ]
}

Node.js v21.1.0
`

**Comment by shamov102** [comment]
I have a same problem, when I try to run this command I get the next message
![image](https://github.com/vercel/next-learn/assets/33152713/ef1044a1-d864-458b-adda-6387a162b9e9)

**Comment by A-Ostrovnyy** [comment]
Faced with same issue as @shamov102  on Windows 11, Node 20.9.0LTS, NPM- 10.1.0

**Comment by kalliattShibin** [comment]
I had similar error, but not this one. It was a web socket error. What I have done is, go to vercel dashboard->storage->settings->Reset Credentials and reset your credentials. Then copy the new credentials to your .env file. Then it gets connected.

**Comment by marekopatril** [comment]
@A-Ostrovnyy I had same error. Check in your `.env` if you have all values filled I had:
`POSTGRES_USER=""`
`POSTGRES_PASSWORD=""`

after refresh on Vercel site  it suddenly gave me those values, then it worked

**Comment by Connor-Skudlarek** [comment]
I think this step is a little early in the process, but have you deployed your app to Vercel yet?

It could be that you're having a firewall issue. If it also fails when deployed to Vercel, it likely means something else is the matter.

**Comment by StephDietz** [comment]
Thank you for the feedback! I have been seeing an issue where not all of the credentials are being copied over correctly from the clipboard in the Vercel dashboard. Please make sure that all the environment variable have values in your `.env` file. You should have the following:

```
POSTGRES_URL=
POSTGRES_PRISMA_URL=
POSTGRES_URL_NON_POOLING=
POSTGRES_USER=
POSTGRES_HOST=
POSTGRES_PASSWORD=
POSTGRES_DATABASE=
```

This should fix the issue :) I have added a note to the course for troubleshooting this
