### ISSUE TITLE
Issue with Seeding PostgreSQL

### ISSUE THREAD

**Issue by DewaldtVR** [vercel/next-learn#385]
npm run seed        

> seed
> node -r dotenv/config ./scripts/seed.js

Error seeding users: error: no such user
    at on.parseErrorMessage (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1174:6)
    at on.handlePacket (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1135:48)
    at on.parse (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1119:63)
    at x.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1181:74)
    at x.emit (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:395:63)
    at WebSocket.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:992:19)
    at callListener (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:515:28)
    at Receiver.receiverOnMessage (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\websocket.js:1192:20) {
  length: 33,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined
}
An error occurred while attempting to seed the database: error: no such user
    at on.parseErrorMessage (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1174:6)
    at on.handlePacket (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1135:48)
    at on.parse (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1119:63)
    at x.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1181:74)
    at x.emit (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:395:63)
    at WebSocket.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:992:19)
    at callListener (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:515:28)
    at Receiver.receiverOnMessage (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\websocket.js:1192:20) {
  length: 33,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined
}
C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:394
throw o;var u=new Error("Unhandled error."+(o?" ("+o.message+")":""));throw u.context=
^

Error: Connection terminated unexpectedly
    at cn.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1241:44)
    at Object.onceWrapper (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:408:39)
    at cn.emit (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:395:63)
    at x.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:1193:66)
    at x.emit (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:395:63)
    at WebSocket.<anonymous> (C:\Users\vanre\nextjs-dashboard\node_modules\@neondatabase\serverless\index.js:990:76)
    at callListener (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onClose (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\event-target.js:220:9)
    at WebSocket.emit (node:events:515:28)
    at WebSocket.emitClose (C:\Users\vanre\nextjs-dashboard\node_modules\ws\lib\websocket.js:260:10)

Node.js v21.1.0

**Comment by DewaldtVR** [comment]
The issue is, when copying the .env from Vercel, you should click the "Show Secret" button before copy and paste. Then run it again :)

**Comment by DewaldtVR** [comment]
Awesome! Good luck!
