### ISSUE TITLE
Chapter 6 npm run seed failed : SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by li7819559** [vercel/next-learn#467]
nextjs-dashboard % npm run seed                                                             

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1070:8)
    at ssl.onhandshakedone (node:_tls_wrap:856:12)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/lx/copilotProject/nextjs-hello/nextjs-dashboard/node_modules/ws/lib/websocket.js:1016:13)
    at ClientRequest.<anonymous> (/Users/lx/copilotProject/nextjs-hello/nextjs-dashboard/node_modules/ws/lib/websocket.js:864:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}

**Comment by li7819559** [comment]
Node.js v20.9.0 
![image](https://github.com/vercel/next-learn/assets/42015000/83900701-94ba-4941-8097-3726714a3c29)
