### ISSUE TITLE
Chapter 6 nodejs error

### ISSUE THREAD

**Issue by SecYJ** [vercel/next-learn#478]
I got this error when add const revenue = await fetchRevnue.
I have been trying to delete node_modules and reinstall it but it doesnt work
node version - 20.9.0
os - mac and window both have same error

```javascript
 ModuleBuildError: error - node_modules/node-gyp-build/node-gyp-build.js:22:9

  20 |
  21 | function load (dir) {
> 22 |   return runtimeRequire(load.resolve(dir))
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 | }
  24 |
  25 | load.resolve = load.path = function (dir) {
Module not found
It was not possible to find the requested file.
    Parsed request as written in source code: dynamic
    Path where resolving has started: [project]/node_modules/node-gyp-build/node-gyp-build.js
    Type of request: commonjs request
    Import map: No import map entry
    

error - node_modules/.pnpm/node-gyp-build@4.7.0/node_modules/node-gyp-build/node-gyp-build.js:22:9

  20 |
  21 | function load (dir) {
> 22 |   return runtimeRequire(load.resolve(dir))
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 | }
  24 |
  25 | load.resolve = load.path = function (dir) {
Module not found
It was not possible to find the requested file.
    Parsed request as written in source code: dynamic
    Path where resolving has started: [project]/node_modules/.pnpm/node-gyp-build@4.7.0/node_modules/node-gyp-build/node-gyp-build.js
    Type of request: commonjs request
    Import map: No import map entry
    
    at processIssues (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:267:23)
    at Object.ensurePage (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:1107:33)
    at async DevBundlerService.ensurePage (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:519:9)
    at async Object.ensure (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:164:17)
    at async DevRouteMatcherManager.matchAll (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
    at async DevRouteMatcherManager.match (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:222:31)
    at async DevServer.handleRequestImpl (/Users/dontdiepls123/Desktop/nextjs-dashboard/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:798:17)
```

**Comment by StephDietz** [comment]
@SecYJ can you provide more info? Which chapter was this in?

**Comment by leerob** [comment]
Closing as no additional information has been provided, but let us know!

**Comment by LinkSky109** [comment]
> 中方能否提供更多信息？这是在哪一章？
npm cache clean --force
rm -rf node_modules package-lock.json
npm install

**Comment by LinkSky109** [comment]
> @SecYJ can you provide more info? Which chapter was this in?

npm cache clean --force
rm -rf node_modules package-lock.json
npm install
