### ISSUE TITLE
Chaper 6: Seeding Error

### ISSUE THREAD

**Issue by Mehmet-Wesim** [vercel/next-learn#479]
Dear team, I am following the setting up database steps facing following error. Kindly advise
PS C:\nextjs-dashboard> npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

An error occurred while attempting to seed the database: VercelPostgresError: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
    at createPool (C:\Development\NextJS\nextjs-dashboard\node_modules\@vercel\postgres\dist\chunk-PKSWROYW.cjs:158:11)
    at Object.get (C:\Development\NextJS\nextjs-dashboard\node_modules\@vercel\postgres\dist\chunk-PKSWROYW.cjs:201:16)
    at main (C:\Development\NextJS\nextjs-dashboard\scripts\seed.js:164:27)
    at Object.<anonymous> (C:\Development\NextJS\nextjs-dashboard\scripts\seed.js:174:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'missing_connection_string'
}

**Comment by Mehmet-Wesim** [comment]
@DevChauhan5 , Thank you for your support.
I had made a mistake in updated the .env file. Make the corrections and the script is functional now.
