### ISSUE TITLE
Chapter 6 - Seeding error - SelfSigned Certificate Error

### ISSUE THREAD

**Issue by kumarjeyaprakasam** [vercel/next-learn#486]
Hi,

I am not able to seed the database using the instruction on chapter 6. 
The following error while executing
```
> seed
> node -r dotenv/config ./scripts/seed.js

node:events:505....] / : timing npm:load Completed in 49ms
      throw er; // Unhandled 'error' event
      ^

Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1531:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:945:8)
    at ssl.onhandshakedone (node:_tls_wrap:726:12)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\Code\nextjstutorials\socotra-dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (C:\Code\nextjstutorials\socotra-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:462:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}

```

Could you please help?

**Comment by kumarjeyaprakasam** [comment]
![Screenshot 2023-11-26 092518](https://github.com/vercel/next-learn/assets/1309449/8e287fcb-9ecd-4f1b-b50f-d6eb40dbcc9b)

**Comment by delbaoliveira** [comment]
Hey there @kumarjeyaprakasam 👋🏼  Are you still seeing `connecting` on the Vercel dashboard?

**Comment by kumarjeyaprakasam** [comment]
Hi,
I got that resolved. it was my Global protect on my laptop which was restricting the access. Thanks for the support
with regards,
Kumar Jeyaprakasam
***@***.***
 

    On Tuesday, 28 November, 2023 at 10:41:49 am GMT, Delba de Oliveira ***@***.***> wrote:  
 
 


Hey there @kumarjeyaprakasam 👋🏼 Are you still seeing connecting on the Vercel dashboard?

**Comment by joelcipriano** [comment]
I'm getting quite the same error:

```
yarn run v1.22.19
$ node -r dotenv/config ./scripts/seed.js
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'dotenv/config'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1433:5)
    at loadPreloadModules (node:internal/process/pre_execution:611:5)
    at setupUserModules (node:internal/process/pre_execution:130:3)
    at prepareExecution (node:internal/process/pre_execution:113:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:40:3)
    at node:internal/main/run_main_module:10:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v18.18.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jpkdomgen** [comment]
> Hey there @kumarjeyaprakasam 👋🏼 Are you still seeing `connecting` on the Vercel dashboard?

No, It got resolved.

**Comment by jpkdomgen** [comment]
I set this variable NODE_TLS_REJECT_UNAUTHORIZED=0 and the self-signed issue went away. Now I can seed the database.

**Comment by joelcipriano** [comment]
Resolved it here.

I'm following the Learn Next.js examples and, at the same time, prototyping another app.

The error was appearing in this other app and not in the nextjs-dashboard of the exercise.

The problem was the lack of the "dotenv" package.

Just install it and the seed worked perfectly.

Thank you and sorry for the confusion.

**Comment by shohei918** [comment]
I encountered the same issue and resolved by adding NODE_TLS_REJECT_UNAUTHORIZED=0 in .env file.

**Comment by LAWTED** [comment]
The main reason is lack of "dontenv" package. And the NODE_TLS_REJECT_UNAUTHORIZED=0 method not works on me.

Try 
```
npm install dotenv --sav
```
