### ISSUE TITLE
Missing connection string

### ISSUE THREAD

**Issue by thenftdoctor** [vercel/next-learn#510]
I'm running into a problem after creating a vercel postgres db and connecting it to my project.
I changed .env.example into .env and copy pasted the .env.local secrets. 
I also ran the "vercel env pull .env.development.local" and "npm install @vercel/postgres" commands as per vercels instructions. Then I run into the following problem of seeding the database with the "npm run seed" command:

npm run seed

> seed
> node -r dotenv/config ./nextjs-dashboard/scripts/seed.js

An error occurred while attempting to seed the database: VercelPostgresError: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
    at createPool (/Users/andor/Desktop/next_course_app/nextjs-dashboard/node_modules/@vercel/postgres/dist/chunk-PKSWROYW.cjs:158:11)
    at Object.get (/Users/andor/Desktop/next_course_app/nextjs-dashboard/node_modules/@vercel/postgres/dist/chunk-PKSWROYW.cjs:201:16)
    at main (/Users/andor/Desktop/next_course_app/nextjs-dashboard/scripts/seed.js:164:27)
    at Object.<anonymous> (/Users/andor/Desktop/next_course_app/nextjs-dashboard/scripts/seed.js:174:1)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'missing_connection_string'
}

Can anyone help please? I would like to proceed with the course, but I'm stuck at this part.

**Comment by sugarboo** [comment]
Same problem as you. I found a solution in [issue#484](https://github.com/vercel/next-learn/issues/484#issuecomment-1845396924).

**Comment by thenftdoctor** [comment]
Thnx @sugarboo. It worked for me too.
So the solution is to not use .env.example, but after having run "vercel env pull .env.development.local" change the .env.development.local file name to .env and then run "mpn run seed".
Could hardly believe it when I finally saw the script running :)

**Comment by warrengoldman** [comment]
Having same issue. However I do not have a .env.development.local OR a .env.local file? only a .env.example

Ideas?

**Comment by dipeshsgdl** [comment]
Changing the name worked for me too! Had error about connection string missing when trying to seed. Mine had file name .env.example which I changed to .env

**Comment by lpoulter1** [comment]
oh you can point to the config
`    "seed": "node -r dotenv/config ./scripts/seed.js dotenv_config_path=.env.development.local"`

**Comment by M-Anonymous** [comment]
maybe you get the env not in the server component,but in the client component.

**Comment by leerob** [comment]
We're improving the seed process here so you can hit a URL in the browser: https://github.com/vercel/next-learn/pull/764
