### ISSUE TITLE
Chapter 6 Seed  database error "ECONNRESET"

### ISSUE THREAD

**Issue by wanglin1329** [vercel/next-learn#529]
![微信图片_20231228230029](https://github.com/vercel/next-learn/assets/151656807/814c766a-3712-4b90-bb45-5e14e54403b4)

D:\webstorm\nextjs-dashboard>npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (D:\webstorm\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (D:\webstorm\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v20.9.0

I'm a beginner and have installed Node.js v20.9.0 on both computers. I'm encountering an error at the same spot, and despite the mention in issues/476 about installing the 'dotenv' package, I've installed it but am still facing errors.

**Comment by leerob** [comment]
Could you try running the command again? Or maybe a different Node.js version?
