### ISSUE TITLE
Chapter 6 - Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by GiovanniFernandes** [vercel/next-learn#551]
```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)      
    at ClientRequest.<anonymous> (C:\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}

Node.js v20.10.0
```

**Comment by heartkey** [comment]
i have same issue

**Comment by vanandtwocrows** [comment]
I had the same problem.
I think this is something to do with my internet connection settings, potentially with VPN config.
When using a different internet connection (I used mobile data), this step worked for me.

I will add more to this comments if I find out more.

**Comment by leerob** [comment]
I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!
