### ISSUE TITLE
Unable to get issuer cert locally

### ISSUE THREAD

**Issue by ginger-collins** [vercel/next-learn#606]
when using "npm run seed" I get get and error return "UNABLE_TO_GET_ISSUER_CERT_LOCALLY". 
I am on Windows 10

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\Repo\Github\personal\Next-JS-Dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (C:\Repo\Github\personal\Next-JS-Dashboard\node_modules\ws\lib\websocket.js:864:5
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}

Node.js v20.11.1

**Comment by keyty-str** [comment]
I have the same error,Did you solved it?

**Comment by AlessandroMarc** [comment]
Same here!
