### ISSUE TITLE
In Chapter 7,Failed to fetch revenue data.

### ISSUE THREAD

**Issue by J3020605821** [vercel/next-learn#630]
This is the interface:
![图片](https://github.com/vercel/next-learn/assets/104178424/de378336-c43d-403f-8304-6fde125fb26d)

This is a project console error：
Database Error: NeonDbError: Error connecting to database: fetch failed
    at execute (webpack-internal:///(rsc)/./node_modules/@neondatabase/serverless/index.mjs:1547:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchRevenue (webpack-internal:///(rsc)/./app/lib/data.ts:25:22)
    at async Page (webpack-internal:///(rsc)/./app/dashboard/page.tsx:15:21) {
  code: null,
  sourceError: TypeError: fetch failed
      at node:internal/deps/undici/undici:12344:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async globalThis.fetch (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:216:16)
      at async execute (webpack-internal:///(rsc)/./node_modules/@neondatabase/serverless/index.mjs:1546:43)
      at async fetchRevenue (webpack-internal:///(rsc)/./app/lib/data.ts:25:22)
      at async Page (webpack-internal:///(rsc)/./app/dashboard/page.tsx:15:21) {
    cause: AggregateError
        at internalConnectMultiple (node:net:1114:18)
        at internalConnectMultiple (node:net:1177:5)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      code: 'ETIMEDOUT',
      [errors]: [Array]
    }
  }
}
 ⨯ app/lib/data.ts (31:10) @ fetchRevenue
 ⨯ Error: Failed to fetch revenue data.
    at fetchRevenue (./app/lib/data.ts:30:15)
    at async Page (./app/dashboard/page.tsx:15:21)
  29 |   } catch (error) {
  30 |     console.error('Database Error:', error);
> 31 |     throw new Error('Failed to fetch revenue data.');
     |          ^
  32 |   }
  33 | }
  34 |
Seed your database completed
And only when running locally can this be done. Deploying it to Vercel can display a bar chart
Why did it go wrong? Which kind-hearted person can help solve it

**Comment by vignxs** [comment]
everyone facing the same error

**Comment by J3020605821** [comment]
Does anyone know how to link to a local database

**Comment by vignxs** [comment]
try running vercel dev instead of npm run dev

that did the magic for me
https://github.com/orgs/vercel/discussions/2350#discussioncomment-5850746

**Comment by J3020605821** [comment]
ry running vercel dev 
Failed to fetch user: NeonDbError: Error connecting to database: fetch failed

**Comment by fath-nasrudin** [comment]
I face the same problem. Have you solved this problem?

**Comment by kmr-ankitt** [comment]
how did you fix this issue?

**Comment by evanmarshall-dev** [comment]
I am having the same issue and running `vercel dev` does not work. I have updated all of the code from the Github repo for this course under "final-example." Still same issue. I can not get past Chapter 7 because I receive a catch error 

`} catch (error) {
  81 |     console.error("Database Error:", error);
> 82 |     throw new Error("Failed to fetch card data.");
     |           ^
  83 |   }
  84 | }`

Everytime I try to fetch any of the data for the dashboard overview (revenue, invoices, and cards).

**Comment by m1ndaugasdirma** [comment]
```
`import postgres from 'postgres';
import {
  CustomerField,
  CustomersTableType,
  InvoiceForm,
  InvoicesTable,
  LatestInvoiceRaw,
  Revenue,
} from './definitions';
import { formatCurrency } from './utils';

// Initialize the postgres client
const sql = postgres(`${process.env.POSTGRES_URL}`);

export async function fetchRevenue() {
  try {
    console.log('Fetching revenue data...');
    const data = await sql<Revenue[]>`SELECT * FROM revenue`;
    console.log('Data fetch completed.');

    return data;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch revenue data.');
  }
}

export async function fetchLatestInvoices() {
  try {
    const data = await sql<LatestInvoiceRaw[]>`
      SELECT invoices.amount, customers.name, customers.image_url, customers.email, invoices.id
      FROM invoices
      JOIN customers ON invoices.customer_id = customers.id
      ORDER BY invoices.date DESC
      LIMIT 5`;

    const latestInvoices = data.map((invoice) => ({
      ...invoice,
      amount: formatCurrency(invoice.amount),
    }));
    return latestInvoices;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch the latest invoices.');
  }
}

export async function fetchCardData() {
  try {
    const invoiceCountPromise = sql`SELECT COUNT(*) FROM invoices`;
    const customerCountPromise = sql`SELECT COUNT(*) FROM customers`;
    const invoiceStatusPromise = sql`
      SELECT
        SUM(CASE WHEN status = 'paid' THEN amount ELSE 0 END) AS "paid",
        SUM(CASE WHEN status = 'pending' THEN amount ELSE 0 END) AS "pending"
      FROM invoices`;

    const [invoiceCountResult, customerCountResult, invoiceStatusResult] = await Promise.all([
      invoiceCountPromise,
      customerCountPromise,
      invoiceStatusPromise,
    ]);

    const numberOfInvoices = Number(invoiceCountResult[0].count ?? '0');
    const numberOfCustomers = Number(customerCountResult[0].count ?? '0');
    const totalPaidInvoices = formatCurrency(invoiceStatusResult[0].paid ?? '0');
    const totalPendingInvoices = formatCurrency(invoiceStatusResult[0].pending ?? '0');

    return {
      numberOfCustomers,
      numberOfInvoices,
      totalPaidInvoices,
      totalPendingInvoices,
    };
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch card data.');
  }
}

const ITEMS_PER_PAGE = 6;
export async function fetchFilteredInvoices(query: string, currentPage: number) {
  const offset = (currentPage - 1) * ITEMS_PER_PAGE;

  try {
    const invoices = await sql<InvoicesTable[]>`
      SELECT
        invoices.id,
        invoices.amount,
        invoices.date,
        invoices.status,
        customers.name,
        customers.email,
        customers.image_url
      FROM invoices
      JOIN customers ON invoices.customer_id = customers.id
      WHERE
        customers.name ILIKE ${'%' + query + '%'} OR
        customers.email ILIKE ${'%' + query + '%'} OR
        invoices.amount::text ILIKE ${'%' + query + '%'} OR
        invoices.date::text ILIKE ${'%' + query + '%'} OR
        invoices.status ILIKE ${'%' + query + '%'}
      ORDER BY invoices.date DESC
      LIMIT ${ITEMS_PER_PAGE} OFFSET ${offset}
    `;

    return invoices;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch invoices.');
  }
}

export async function fetchInvoicesPages(query: string) {
  try {
    const count = await sql`
      SELECT COUNT(*)
      FROM invoices
      JOIN customers ON invoices.customer_id = customers.id
      WHERE
        customers.name ILIKE ${'%' + query + '%'} OR
        customers.email ILIKE ${'%' + query + '%'} OR
        invoices.amount::text ILIKE ${'%' + query + '%'} OR
        invoices.date::text ILIKE ${'%' + query + '%'} OR
        invoices.status ILIKE ${'%' + query + '%'}
    `;

    const totalPages = Math.ceil(Number(count[0].count) / ITEMS_PER_PAGE);
    return totalPages;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch total number of invoices.');
  }
}

export async function fetchInvoiceById(id: string) {
  try {
    const data = await sql<InvoiceForm[]>`
      SELECT
        invoices.id,
        invoices.customer_id,
        invoices.amount,
        invoices.status
      FROM invoices
      WHERE invoices.id = ${id};
    `;

    const invoice = data.map((invoice) => ({
      ...invoice,
      amount: invoice.amount / 100, // Convert amount from cents to dollars
    }));

    return invoice[0];
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch invoice.');
  }
}

export async function fetchCustomers() {
  try {
    const customers = await sql<CustomerField[]>`
      SELECT
        id,
        name
      FROM customers
      ORDER BY name ASC
    `;

    return customers;
  } catch (err) {
    console.error('Database Error:', err);
    throw new Error('Failed to fetch all customers.');
  }
}

export async function fetchFilteredCustomers(query: string) {
  try {
    const customers = await sql<CustomersTableType[]>`
      SELECT
        customers.id,
        customers.name,
        customers.email,
        customers.image_url,
        COUNT(invoices.id) AS total_invoices,
        SUM(CASE WHEN invoices.status = 'pending' THEN invoices.amount ELSE 0 END) AS total_pending,
        SUM(CASE WHEN invoices.status = 'paid' THEN invoices.amount ELSE 0 END) AS total_paid
      FROM customers
      LEFT JOIN invoices ON customers.id = invoices.customer_id
      WHERE
        customers.name ILIKE ${'%' + query + '%'} OR
        customers.email ILIKE ${'%' + query + '%'}
      GROUP BY customers.id, customers.name, customers.email, customers.image_url
      ORDER BY customers.name ASC
    `;

    const formattedCustomers = customers.map((customer) => ({
      ...customer,
      total_pending: formatCurrency(customer.total_pending),
      total_paid: formatCurrency(customer.total_paid),
    }));

    return formattedCustomers;
  } catch (err) {
    console.error('Database Error:', err);
    throw new Error('Failed to fetch customer table.');
  }
}
`
```

**Comment by mayankwalia** [comment]
Using`vercel dev` solved the issue for me

**Comment by just2a** [comment]
> ```
> import postgres from 'postgres';
> import {
>   CustomerField,
>   CustomersTableType,
>   InvoiceForm,
>   InvoicesTable,
>   LatestInvoiceRaw,
>   Revenue,
> } from './definitions';
> import { formatCurrency } from './utils';
> 
> // Initialize the postgres client
> const sql = postgres(`${process.env.POSTGRES_URL}`);
> 
> export async function fetchRevenue() {
>   try {
>     console.log('Fetching revenue data...');
>     const data = await sql<Revenue[]>`SELECT * FROM revenue`;
>     console.log('Data fetch completed.');
> 
>     return data;
>   } catch (error) {
>     console.error('Database Error:', error);
>     throw new Error('Failed to fetch revenue data.');
>   }
> }
> 
> export async function fetchLatestInvoices() {
>   try {
>     const data = await sql<LatestInvoiceRaw[]>`
>       SELECT invoices.amount, customers.name, customers.image_url, customers.email, invoices.id
>       FROM invoices
>       JOIN customers ON invoices.customer_id = customers.id
>       ORDER BY invoices.date DESC
>       LIMIT 5`;
> 
>     const latestInvoices = data.map((invoice) => ({
>       ...invoice,
>       amount: formatCurrency(invoice.amount),
>     }));
>     return latestInvoices;
>   } catch (error) {
>     console.error('Database Error:', error);
>     throw new Error('Failed to fetch the latest invoices.');
>   }
> }
> 
> export async function fetchCardData() {
>   try {
>     const invoiceCountPromise = sql`SELECT COUNT(*) FROM invoices`;
>     const customerCountPromise = sql`SELECT COUNT(*) FROM customers`;
>     const invoiceStatusPromise = sql`
>       SELECT
>         SUM(CASE WHEN status = 'paid' THEN amount ELSE 0 END) AS "paid",
>         SUM(CASE WHEN status = 'pending' THEN amount ELSE 0 END) AS "pending"
>       FROM invoices`;
> 
>     const [invoiceCountResult, customerCountResult, invoiceStatusResult] = await Promise.all([
>       invoiceCountPromise,
>       customerCountPromise,
>       invoiceStatusPromise,
>     ]);
> 
>     const numberOfInvoices = Number(invoiceCountResult[0].count ?? '0');
>     const numberOfCustomers = Number(customerCountResult[0].count ?? '0');
>     const totalPaidInvoices = formatCurrency(invoiceStatusResult[0].paid ?? '0');
>     const totalPendingInvoices = formatCurrency(invoiceStatusResult[0].pending ?? '0');
> 
>     return {
>       numberOfCustomers,
>       numberOfInvoices,
>       totalPaidInvoices,
>       totalPendingInvoices,
>     };
>   } catch (error) {
>     console.error('Database Error:', error);
>     throw new Error('Failed to fetch card data.');
>   }
> }
> 
> const ITEMS_PER_PAGE = 6;
> export async function fetchFilteredInvoices(query: string, currentPage: number) {
>   const offset = (currentPage - 1) * ITEMS_PER_PAGE;
> 
>   try {
>     const invoices = await sql<InvoicesTable[]>`
>       SELECT
>         invoices.id,
>         invoices.amount,
>         invoices.date,
>         invoices.status,
>         customers.name,
>         customers.email,
>         customers.image_url
>       FROM invoices
>       JOIN customers ON invoices.customer_id = customers.id
>       WHERE
>         customers.name ILIKE ${'%' + query + '%'} OR
>         customers.email ILIKE ${'%' + query + '%'} OR
>         invoices.amount::text ILIKE ${'%' + query + '%'} OR
>         invoices.date::text ILIKE ${'%' + query + '%'} OR
>         invoices.status ILIKE ${'%' + query + '%'}
>       ORDER BY invoices.date DESC
>       LIMIT ${ITEMS_PER_PAGE} OFFSET ${offset}
>     `;
> 
>     return invoices;
>   } catch (error) {
>     console.error('Database Error:', error);
>     throw new Error('Failed to fetch invoices.');
>   }
> }
> 
> export async function fetchInvoicesPages(query: string) {
>   try {
>     const count = await sql`
>       SELECT COUNT(*)
>       FROM invoices
>       JOIN customers ON invoices.customer_id = customers.id
>       WHERE
>         customers.name ILIKE ${'%' + query + '%'} OR
>         customers.email ILIKE ${'%' + query + '%'} OR
>         invoices.amount::text ILIKE ${'%' + query + '%'} OR
>         invoices.date::text ILIKE ${'%' + query + '%'} OR
>         invoices.status ILIKE ${'%' + query + '%'}
>     `;
> 
>     const totalPages = Math.ceil(Number(count[0].count) / ITEMS_PER_PAGE);
>     return totalPages;
>   } catch (error) {
>     console.error('Database Error:', error);
>     throw new Error('Failed to fetch total number of invoices.');
>   }
> }
> 
> export async function fetchInvoiceById(id: string) {
>   try {
>     const data = await sql<InvoiceForm[]>`
>       SELECT
>         invoices.id,
>         invoices.customer_id,
>         invoices.amount,
>         invoices.status
>       FROM invoices
>       WHERE invoices.id = ${id};
>     `;
> 
>     const invoice = data.map((invoice) => ({
>       ...invoice,
>       amount: invoice.amount / 100, // Convert amount from cents to dollars
>     }));
> 
>     return invoice[0];
>   } catch (error) {
>     console.error('Database Error:', error);
>     throw new Error('Failed to fetch invoice.');
>   }
> }
> 
> export async function fetchCustomers() {
>   try {
>     const customers = await sql<CustomerField[]>`
>       SELECT
>         id,
>         name
>       FROM customers
>       ORDER BY name ASC
>     `;
> 
>     return customers;
>   } catch (err) {
>     console.error('Database Error:', err);
>     throw new Error('Failed to fetch all customers.');
>   }
> }
> 
> export async function fetchFilteredCustomers(query: string) {
>   try {
>     const customers = await sql<CustomersTableType[]>`
>       SELECT
>         customers.id,
>         customers.name,
>         customers.email,
>         customers.image_url,
>         COUNT(invoices.id) AS total_invoices,
>         SUM(CASE WHEN invoices.status = 'pending' THEN invoices.amount ELSE 0 END) AS total_pending,
>         SUM(CASE WHEN invoices.status = 'paid' THEN invoices.amount ELSE 0 END) AS total_paid
>       FROM customers
>       LEFT JOIN invoices ON customers.id = invoices.customer_id
>       WHERE
>         customers.name ILIKE ${'%' + query + '%'} OR
>         customers.email ILIKE ${'%' + query + '%'}
>       GROUP BY customers.id, customers.name, customers.email, customers.image_url
>       ORDER BY customers.name ASC
>     `;
> 
>     const formattedCustomers = customers.map((customer) => ({
>       ...customer,
>       total_pending: formatCurrency(customer.total_pending),
>       total_paid: formatCurrency(customer.total_paid),
>     }));
> 
>     return formattedCustomers;
>   } catch (err) {
>     console.error('Database Error:', err);
>     throw new Error('Failed to fetch customer table.');
>   }
> }
> 
> ```

I update app/lib/data.ts as mentioned above,  also with `pnpm install postgres` . Everything works here, seems like there exists problems using '@vercel/postgres'

**Comment by shwosner** [comment]
Solution:

In `/app/lib/data.ts`, I added `client.sql` instead of `sql` and that fixed it for me 🤷 

```
- import { sql } from "@vercel/postgres";
+ import { db } from "@vercel/postgres";
+ const client = await db.connect();
...
- const data = await sql<Revenue>`SELECT * FROM revenue`;
+ const data = await client.sql<Revenue>`SELECT * FROM revenue`;
```

**Comment by DTheArtist** [comment]
> Solution:
> 
> In `/app/lib/data.ts`, I added `client.sql` instead of `sql` and that fixed it for me 🤷
> 
> ```
> - import { sql } from "@vercel/postgres";
> + import { db } from "@vercel/postgres";
> + const client = await db.connect();
> ...
> - const data = await sql<Revenue>`SELECT * FROM revenue`;
> + const data = await client.sql<Revenue>`SELECT * FROM revenue`;
> ```
> 
> Make sure you do `client.release();`

Where do you place `client.release();?

**Comment by DTheArtist** [comment]
This solution worked for [Supabase](https://github.com/vercel/next-learn/issues/630#issuecomment-2492966500) Thanks @shwosner for your generosity. The fetch was slow so I am concerned about that but I am sure a loader or placeholder could be used as loading times are not uncommon. 

I mention the loading time because if you are like me and code or think up ideas faster than the system can refresh, load or propagate you'll miss the fix and think it didn't work for you. So for those who try the about fix, give it a minute to show up locally and then wait a few after committing for vercel to deploy it. 

For an idea of how long to wait, I got trapped in a 2 hour debug session that cause vercel to have a 1 hour delay updating to the latest commit. Maybe, work slow and watch a show to avoid missing the fix.
