### ISSUE TITLE
Chapitre 6: error seeding, when i run npm run seed

### ISSUE THREAD

**Issue by Iangolana** [vercel/next-learn#664]
i have an error when i run the npm run seed, i've already deployed and connect the app in vercel but i got this error when seeding

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:496
      throw er; // Unhandled 'error' event
      ^

AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/iangolana/Projects/nextjs-dashboard/node_modules/ws/lib/websocket.js:1016:13)
    at ClientRequest.<anonymous> (/home/iangolana/Projects/nextjs-dashboard/node_modules/ws/lib/websocket.js:864:5)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 100.26.116.133:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '100.26.116.133',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:540b:c14a:4d57:1251:234d:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:540b:c14a:4d57:1251:234d',
      port: 443
    },
    Error: connect ETIMEDOUT 44.199.59.172:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '44.199.59.172',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:544d:621b:957c:81:5e5b:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:544d:621b:957c:81:5e5b',
      port: 443
    },
    Error: connect ETIMEDOUT 34.194.100.28:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '34.194.100.28',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:5419:4ecf:2a7c:cf52:31ae:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:5419:4ecf:2a7c:cf52:31ae',
      port: 443
    },
    Error: connect ETIMEDOUT 23.23.229.9:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '23.23.229.9',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:543b:a8aa:14fb:d008:11fe:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:543b:a8aa:14fb:d008:11fe',
      port: 443
    },
    Error: connect ETIMEDOUT 44.207.148.149:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '44.207.148.149',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:5421:acd1:6284:5a8a:d6e9:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:5421:acd1:6284:5a8a:d6e9',
      port: 443
    },
    Error: connect ETIMEDOUT 52.20.107.131:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '52.20.107.131',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:5454:82a4:8209:20f8:a5c1:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:5454:82a4:8209:20f8:a5c1',
      port: 443
    }
  ]
}

**Comment by Viveksz** [comment]
Same error i got also.

**Comment by vivek20Eng** [comment]
Same error
> seed
> node -r dotenv/config ./scripts/seed.js

node:events:497
      throw er; // Unhandled 'error' event
      ^

AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1707:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/viveks/Documents/alokin_project/Learn/nextjs-dashboard/node_modules/ws/lib/websocket.js:1016:13)
    at ClientRequest.<anonymous> (/home/viveks/Documents/alokin_project/Learn/nextjs-dashboard/node_modules/ws/lib/websocket.js:864:5)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:492:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 23.23.229.9:443
        at createConnectionError (node:net:1643:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1702:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '23.23.229.9',
      port: 443
    },
    Error: connect ENETUNREACH 2600:1f18:240c:5421:acd1:6284:5a8a:d6e9:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1707:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2600:1f18:240c:5421:acd1:6284:5a8a:d6e9',
      port: 443
    },

**Comment by melodiaz23** [comment]
Same here: 

`> node -r dotenv/config ./scripts/seed.js

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/Users/melidiaz/Documents/portafolio/projects/natuvida/scripts/seed.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2`

**Comment by dalienst** [comment]
I experienced the same problem for a while and created a new postgres database on vercel. This was before I even started the NextJS server `npm run dev` . I started the server then ran the `npm run seed`. I hope this helps. Apparently the server has to be running.

**Comment by elmekkaoui-dev** [comment]
You just need to restart or stop the running server before  executing the `npm run seed` command

**Comment by amiteshore** [comment]
If you're using node 20 and encountering this issue, you can try using node 18 to see if it solves the problem. It worked for me.

Run `nvm install 18`, it will install node 18, then start the next server with `npm run dev`.

**Comment by leerob** [comment]
I am not able to reproduce, but it sounds like if you are seeing this:

- Restart or stop the running server
- If Node.js 20 isn't working, try a different version

Thank you!
