### ISSUE TITLE
Chapter 6: after running seeding script I got console logs that my database had been seeded, but I don't have any data

### ISSUE THREAD

**Issue by Om-Oleksandr** [vercel/next-learn#676]
![image](https://github.com/vercel/next-learn/assets/67714714/973dbdf4-3043-4c41-8d27-37b2417b5366)
![image](https://github.com/vercel/next-learn/assets/67714714/b869421f-0b43-4250-b60b-6020841062af)

**Comment by Om-Oleksandr** [comment]
can this error cause the issue?
![image](https://github.com/vercel/next-learn/assets/67714714/2514f6c8-d9b9-401f-8dd6-99af62e128d4)

**Comment by nirajanach** [comment]
I had a similar problem, I seeded again after stopping server and it seeded after that.

the steps:
1.) stop the server from terminal: Ctrl + x 
2.) run the seeding command: npm run seed
3.) check Postgres Data tab.

**Comment by sAndrin3** [comment]
I had this issue

npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

/home/node/Documents/NextJs/nextjs-dashboard/node_modules/@neondatabase/serverless/index.js:364
a(ko,"BufferBigIntNotDefined")});var b,S,v,w,d,y,p=K(()=>{"use strict";b=globalThis,S=globalThis.setImmediate??(r=>setTimeout(
                                                                                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/node/Documents/NextJs/nextjs-dashboard/node_modules/@vercel/postgres/dist/chunk-PKSWROYW.cjs:2:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    
    **The solution was Upgrading node: nvm install node**
    
    **Result**
    npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

Created "users" table
Seeded 1 users
Created "customers" table
Seeded 10 customers
Created "invoices" table
Seeded 15 invoices
Created "revenue" table
Seeded 12 revenue

**Comment by GaneshSrambikal** [comment]
> I had a similar problem, I seeded again after stopping server and it seeded after that.
> 
> the steps: 1.) stop the server from terminal: Ctrl + x 2.) run the seeding command: npm run seed 3.) check Postgres Data tab.

As you have found the solution, this issue can be closed.

Thank you.
