### ISSUE TITLE
Cannot run `npm run dev`

### ISSUE THREAD

**Issue by andy-h-2016** [vercel/next-learn#73]
After running 
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
```
and `cd` into the `nextjs-blog` folder and running `npm run dev` I get the following error:

```
UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
    at /Users/.../nextjs-blog/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.development.server.js:127:19
    at Object.<anonymous> (/Users/.../nextjs-blog/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.development.server.js:1744:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (Users/.../nextjs-blog/node_modules/next/dist/compiled/react-server-dom-webpack/writer.browser.server.js:6:20)
(node:27686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27686) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Not supported
    at Object.loadConfig [as default] (/Users/.../nextjs-blog/node_modules/next/dist/server/config.js:70:78)
```

I am on Node v10.15.2

**Comment by andy-h-2016** [comment]
Solved by upgrading to Node v14.19.0. The instructions [here](https://nextjs.org/learn/basics/create-nextjs-app/setup) should be updated to match the [system requirements](https://nextjs.org/docs/getting-started#system-requirements) for Next.js 12.1.4
