### ISSUE TITLE
Learn Tutoriel Chapter 1 install and run

### ISSUE THREAD

**Issue by AimadYahyaoui** [vercel/next-learn#759]
Hello everyone, 

Still Friday I have this problem when I create with npx : npm install failed.
But with yarn it work fine 👍 

So when I do a cd to go to the project then run "yarn dev" I have this error (and I have the same with npm, pnpm and yarn):

  ✓ Compiled / in 5s (507 modules)
Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at /nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:329941
    at eJ (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:330136)
    at e6 (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:337763)
    at /nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:328660
    at Array.toJSON (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:329125)
    at stringify (<anonymous>)
    at tn (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:343895)
    at ta (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:344138)
    at ts (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:344636)
    at Timeout._onTimeout (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:327778)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  digest: '391033944'
}
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
digest: "391033944"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/link.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
    at stringify (<anonymous>)
digest: "3716923637"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/layout-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
    at stringify (<anonymous>)
digest: "3069026645"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/error-boundary.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
digest: "1390908532"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/render-from-template-context.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
    at stringify (<anonymous>)
digest: "2193463093"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
digest: "391033944"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
digest: "391033944"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/error-boundary.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
digest: "1390908532"
 ⨯ Error: Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at /nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:329941
    at eJ (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:330136)
    at e6 (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:337763)
    at /nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:328660
    at Array.toJSON (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:329125)
    at stringify (<anonymous>)
    at tn (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:343895)
    at ta (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:344138)
    at ts (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:344636)
    at Timeout._onTimeout (/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:327778)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  digest: '391033944',
  page: '/'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 6.8s (736 modules)
 GET / 500 in 12039ms

I don't now how I can fix this.. I'm learning so what I'm asking you ;) 

Thanks for help

**Comment by AimadYahyaoui** [comment]
I'm on Mac :)

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/issues/754#issuecomment-2185323453

**Comment by AimadYahyaoui** [comment]
it's not the same problem
