### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by broosted** [vercel/next-learn#76]
Hi,

tried npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
cd nextjs-blog
npm run dev

got:

`> @ dev /home/broosted/Documents/high-availability-mode-infra/UI/frontend-app
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
(node:7832) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
    at /home/broosted/Documents/high-availability-mode-infra/UI/frontend-app/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.development.server.js:127:19
    at Object.<anonymous> (/home/broosted/Documents/high-availability-mode-infra/UI/frontend-app/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.development.server.js:1744:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/broosted/Documents/high-availability-mode-infra/UI/frontend-app/node_modules/next/dist/compiled/react-server-dom-webpack/writer.browser.server.js:6:20)
(node:7832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ReferenceError: TextEncoder is not defined
`

**Comment by broosted** [comment]
upgrading node and npm to 
 npm -v
8.8.0
 node -v
v18.0.0

solved it
