### ISSUE TITLE
# Unable to set up the vercel environment during deploying the site.

### ISSUE THREAD

**Issue by jajos12** [vercel/next-learn#771]
# When I after following every instruction I ran vercel from the cli, I also I have tried from the vercel website but it says that it is having a problem the problem log is as follows :
     Creating an optimized production build ...
   ✓ Compiled successfully
   ✓ Linting and checking validity of types
     Collecting page data  .tl [VercelPostgresError]: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
      at tf (C:\Users\My\Programming\nextjs-dashboard\.next\server\app\seed\route.js:60:5026)
      at Object.get (C:\Users\My\Programming\nextjs-dashboard\.next\server\app\seed\route.js:60:6072)
      at C:\Users\My\Programming\nextjs-dashboard\.next\server\app\seed\route.js:1:3990
      at t.a (C:\Users\My\Programming\nextjs-dashboard\.next\server\webpack-runtime.js:1:866)
      at 1507 (C:\Users\My\Programming\nextjs-dashboard\.next\server\app\seed\route.js:1:3883)
      at t (C:\Users\My\Programming\nextjs-dashboard\.next\server\webpack-runtime.js:1:127)
      at C:\Users\My\Programming\nextjs-dashboard\.next\server\app\seed\route.js:1:1176
      at t.a (C:\Users\My\Programming\nextjs-dashboard\.next\server\webpack-runtime.js:1:866)
      at 2920 (C:\Users\My\Programming\nextjs-dashboard\.next\server\app\seed\route.js:1:967)
      at t (C:\Users\My\Programming\nextjs-dashboard\.next\server\webpack-runtime.js:1:127) {
    code: 'missing_connection_string'
  }
  
  > Build error occurred
  Error: Failed to collect page data for /seed
      at C:\Users\My\Programming\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522\node_modules\next\dist\build\utils.js:1274:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    type: 'Error'
  }
     Collecting page data  . ELIFECYCLE  Command failed with exit code 1.
![Uploading Screenshot (46).png…]()

**Comment by guzmanpdro** [comment]
[Here's the solution](https://github.com/vercel/next-learn/issues/768#issuecomment-2190168439), greetings 👨‍💻

**Comment by ZachAlba** [comment]
This can also be resolved by ignoring the failed deployment and skipping ahead to the part where you set up your .env file, and then redeploying. At least I believe that's the step that fixed the error for me after some trial and error.

**Comment by Kashyap-Pandya** [comment]
having same issues , will try what @ZachAlba said.

**Comment by kaijuh** [comment]
I followed the solution as posted by @guzmanpdro which solved the issue of deployment .

After the successful deployment as outline there, these are the steps I followed:

1. I added the folder with the route.ts file once again (app/seed/route.ts)
2. I copy pasted this code `https://github.com/vercel/next-learn/blob/main/dashboard/starter-example/app/seed/route.ts`
3. run pnpm i @vercel/postgres in your terminal to install the [Vercel Postgres SDK](https://vercel.com/docs/storage/vercel-postgres/sdk)
4. Ensure your local development server is running with pnpm run dev and navigate to [localhost:3000/seed](http://localhost:3000/seed) in your browser.
5. When finished, you will see 
a message "Database seeded successfully" in the browser. 
<img width="301" alt="Screenshot 2024-06-30 092628" src="https://github.com/vercel/next-learn/assets/78699106/7a7f0cbd-f970-4062-8543-b2d50eeac791">
Once completed, you can delete this file.

Here are all the steps above 
https://nextjs.org/learn/dashboard-app/setting-up-your-database

I can then run queries and keep following along the tutorial

![image](https://github.com/vercel/next-learn/assets/78699106/713a96e6-78fd-40b8-bdbd-ccce58931b27)

Cheers
