### ISSUE TITLE
Chapter 6 deployment build fails

### ISSUE THREAD

**Issue by zadokdaniel** [vercel/next-learn#788]
following the instructions on chapter 6 to deploy on vercel the following errors occur 

Warnings: 
Warning: Detected "engines": { "node": ">=20.12.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version

Errors: 
```
Collecting page data ...
tl [VercelPostgresError]: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
    at tf (/vercel/path0/.next/server/app/seed/route.js:60:5026)
    at Object.get (/vercel/path0/.next/server/app/seed/route.js:60:6072)
    at /vercel/path0/.next/server/app/seed/route.js:1:3957
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:866)
    at 8854 (/vercel/path0/.next/server/app/seed/route.js:1:3850)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
    at /vercel/path0/.next/server/app/seed/route.js:1:1177
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:866)
    at 3113 (/vercel/path0/.next/server/app/seed/route.js:1:967)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:127) {
  code: 'missing_connection_string'
}
> Build error occurred
Error: Failed to collect page data for /seed
    at /vercel/path0/node_modules/.pnpm/next@15.0.0-rc.0_@babel+core@7.24.7_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f_tdi4orn62rfjbymsd33ya6r2le/node_modules/next/dist/build/utils.js:1274:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

**Comment by nguyenmp** [comment]
Try https://github.com/vercel/next-learn/issues/768#issuecomment-2190168439

**Comment by CrisRamosLazaro** [comment]
The Vercel deployment error I-m getting is from a starter code file (./app/ui/acme-logo.tsx:2:26), saying Type error: Cannot find module '@/app/ui/fonts' or its corresponding type declarations.
![Screenshot 2024-07-04 220151](https://github.com/vercel/next-learn/assets/129693280/8d2c9699-fc54-4d6c-bd84-e5bbad945ab1)

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/commit/d379162091cac7ea4d0e3054a9fb527c00596264
