### ISSUE TITLE
Chapter 6: Cannot seed DataBase

### ISSUE THREAD

**Issue by Gentle-Cannibal** [vercel/next-learn#792]
Good day everyone. 👋
When I try to seed DB I get the next error.

Error: [object Object]
    at getProperError (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\lib\is-error.js:41:12)
    at DevServer.renderToResponseImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\base-server.js:2038:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.pipeImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\base-server.js:908:25)
    at async NextNodeServer.handleCatchallRenderRequest (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\next-server.js:273:17)
    at async DevServer.handleRequestImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\base-server.js:804:17)
    at async XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\lib\router-server.js:175:21)
    at async handleRequest (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\lib\router-server.js:354:24)
    at async requestHandlerImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\lib\router-server.js:378:13)
    at async Server.requestListener (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny\node_modules\next\dist\server\lib\start-server.js:142:13) {
  page: '/seed'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 913ms (810 modules)
 GET /seed 500 in 2243ms

OS: Win 11
Browser: Firefox

What can I do?

**Comment by Gentle-Cannibal** [comment]
The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)

**Comment by qlxxkj** [comment]
I get the same issuse,when i try to seed DB with vscode in local envrionment.

**Comment by ChamithSoyza** [comment]
> The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)

Thanks

**Comment by ifiya** [comment]
> Good day everyone. 👋 When I try to seed DB I get the next error.
> 
> Error: [object Object] at getProperError (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\lib\is-error.js:41:12) at DevServer.renderToResponseImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\base-server.js:2038:53) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async DevServer.pipeImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\base-server.js:908:25) at async NextNodeServer.handleCatchallRenderRequest (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\next-server.js:273:17) at async DevServer.handleRequestImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\base-server.js:804:17) at async XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\dev\next-dev-server.js:339:20 at async Span.traceAsyncFn (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\trace\trace.js:157:20) at async DevServer.handleRequest (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\dev\next-dev-server.js:336:24) at async invokeRender (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\lib\router-server.js:175:21) at async handleRequest (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\lib\router-server.js:354:24) at async requestHandlerImpl (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\lib\router-server.js:378:13) at async Server.requestListener (XXXXXXXXXXXXXXXXXX\Education\nextjs-dashboard\node_modules.pnpm\next@15.0.0-rc.0_react-dom@[19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny](mailto:19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522__ru4vnckpyyafgw46z2uaeehbny)\node_modules\next\dist\server\lib\start-server.js:142:13) { page: '/seed' } ○ Compiling /_error ... ✓ Compiled /_error in 913ms (810 modules) GET /seed 500 in 2243ms
> 
> OS: Win 11 Browser: Firefox
> 
> What can I do?

Have you resolved this question?

**Comment by ifiya** [comment]
> The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)

Could you please tell me more details? I also had this problem.
![image](https://github.com/user-attachments/assets/cef263a4-77b8-42b4-be97-01b44e104707)

**Comment by Gentle-Cannibal** [comment]
> > The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)
> 
> Could you please tell me more details? I also had this problem. ![image](https://private-user-images.githubusercontent.com/44367818/356116668-cef263a4-77b8-42b4-be97-01b44e104707.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDg3MDAsIm5iZiI6MTcyMzEwODQwMCwicGF0aCI6Ii80NDM2NzgxOC8zNTYxMTY2NjgtY2VmMjYzYTQtNzdiOC00MmI0LWJlOTctMDFiNDRlMTA0NzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA5MTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNDlmMTI2MmExMjMxZjgxNmNjNzEwNTIwYTNmMDM3NGVmNjZlNjE0MGZiZGI0ZjhkNWM1ZjcxYmE1MDcwNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4ZujiZ4vZmNrpupXpEyItoj6KuvN0KOSLnm3bYIDWI)

To tell the truth, I don't know what else to say about this. You have to deploy your project onto a Vercel environment, as it is described in the course. Then run that deployed project and use _/seed_ address. I want to say, that I had different problems after this stage and didn't finish the course as a whole. You should be ready for this. 🙂

**Comment by aidinio** [comment]
About the problem with seeding the local postgres database, I have edited the `route.ts`  file so seeding a local postgres database would be possible in the dashboard project. You can look at the file [here](https://gist.github.com/aidinio/c5ca01bc236ee804c7caea2be8f38a68).

**Comment by ifiya** [comment]
> About the problem with seeding the local postgres database, I have edited the `route.ts` file so seeding a local postgres database would be possible in the dashboard project. You can look at the file [here](https://gist.github.com/aidinio/c5ca01bc236ee804c7caea2be8f38a68).

Okay, thanks so much.

**Comment by KinonoChen** [comment]
> The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)

hello! I'm having this problem: I can successfully seed an application that I deployed on vercel, but it keeps failing to seed locally, maybe vercel doesn't support local connections to vercel/postgres?

**Comment by aidinio** [comment]
> > The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)
> 
> hello! I'm having this problem: I can successfully seed an application that I deployed on vercel, but it keeps failing to seed locally, maybe vercel doesn't support local connections to vercel/postgres?

Copy my [gist](https://gist.github.com/aidinio/c5ca01bc236ee804c7caea2be8f38a68). It should fix your problem.

**Comment by sergealagon** [comment]
> > > The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)
> > 
> > 
> > hello! I'm having this problem: I can successfully seed an application that I deployed on vercel, but it keeps failing to seed locally, maybe vercel doesn't support local connections to vercel/postgres?
> 
> Copy my [gist](https://gist.github.com/aidinio/c5ca01bc236ee804c7caea2be8f38a68). It should fix your problem.


i did this and it works! now i'm stuck at next chapter. since as per nextjs guide:

> Note: If you used your own database provider in Chapter 6, you'll need to update the database queries to work with your provider. You can find the queries in /app/lib/data.ts.

what adjustments did you do for data.ts?

**Comment by aidinio** [comment]
> > > > The right answer is here. You should start a deployed project on _vercel.com_. And there use _/seed_ address. Because I run local project. It was a mistake.)
> > > 
> > > 
> > > hello! I'm having this problem: I can successfully seed an application that I deployed on vercel, but it keeps failing to seed locally, maybe vercel doesn't support local connections to vercel/postgres?
> > 
> > 
> > Copy my [gist](https://gist.github.com/aidinio/c5ca01bc236ee804c7caea2be8f38a68). It should fix your problem.
> 
> i did this and it works! now i'm stuck at next chapter. since as per nextjs guide:
> 
> > Note: If you used your own database provider in Chapter 6, you'll need to update the database queries to work with your provider. You can find the queries in /app/lib/data.ts.
> 
> what adjustments did you do for data.ts?

The default SQL queries worked for me. I just had a problem with typescript giving me errors for type. So I had to change types to arrays, for example, I had to change 
```typescript
const data = await sql<InvoiceForm>`
      SELECT
        invoices.id,
        invoices.customer_id,
        invoices.amount,
        invoices.status
      FROM invoices
      WHERE invoices.id = ${id};
    `;
```
to this:
```typescript
const data = await sql<InvoiceForm[]>`
      SELECT
        invoices.id,
        invoices.customer_id,
        invoices.amount,
        invoices.status
      FROM invoices
      WHERE invoices.id = ${id};
    `;
```
I think I made some minor adjustments to return values. For example, instead of returning `data`, I returned `data[0]`. I'm not sure what exact change I did to return values, but I'm sure you'll be able to fix it if you spend a little time tweaking it.

**Comment by andrezatcascais** [comment]
> About the problem with seeding the local postgres database, I have edited the `route.ts` file so seeding a local postgres database would be possible in the dashboard project. You can look at the file [here](https://gist.github.com/aidinio/c5ca01bc236ee804c7caea2be8f38a68).

Thank you! Show

**Comment by wyking1997** [comment]
After doing @aidinio 's change, I still had issues at the next chapter. To fix these issues I had to change the lib/data.ts like bellow
`import {
  CustomerField,
  CustomersTableType,
  InvoiceForm,
  InvoicesTable,
  LatestInvoiceRaw,
  Revenue,
} from './definitions';
import { client } from "../seed/route";

import { formatCurrency } from './utils';

export async function fetchRevenue() {
  try {
    // Artificially delay a response for demo purposes.
    // Don't do this in production :)

    // console.log('Fetching revenue data...');
    // await new Promise((resolve) => setTimeout(resolve, 3000));

    const data = await client.sql`SELECT * FROM revenue`;

    // console.log('Data fetch completed after 3 seconds.');

    return data;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch revenue data.');
  }
}

export async function fetchLatestInvoices() {
  try {
    const data = await client.sql`
      SELECT invoices.amount, customers.name, customers.image_url, customers.email, invoices.id
      FROM invoices
      JOIN customers ON invoices.customer_id = customers.id
      ORDER BY invoices.date DESC
      LIMIT 5`;

    const latestInvoices = data.map((invoice) => ({
      ...invoice,
      amount: formatCurrency(invoice.amount),
    }));
    return latestInvoices;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch the latest invoices.');
  }
}

export async function fetchCardData() {
  try {
    // You can probably combine these into a single SQL query
    // However, we are intentionally splitting them to demonstrate
    // how to initialize multiple queries in parallel with JS.
    const invoiceCountPromise = client.sql`SELECT COUNT(*) FROM invoices`;
    const customerCountPromise = client.sql`SELECT COUNT(*) FROM customers`;
    const invoiceStatusPromise = client.sql`SELECT
         SUM(CASE WHEN status = 'paid' THEN amount ELSE 0 END) AS "paid",
         SUM(CASE WHEN status = 'pending' THEN amount ELSE 0 END) AS "pending"
         FROM invoices`;

    const data = await Promise.all([
      invoiceCountPromise,
      customerCountPromise,
      invoiceStatusPromise,
    ]);

    const numberOfInvoices = Number(data[0].count ?? '0');
    const numberOfCustomers = Number(data[1].count ?? '0');
    const totalPaidInvoices = formatCurrency(data[2].paid ?? '0');
    const totalPendingInvoices = formatCurrency(data[2].pending ?? '0');

    return {
      numberOfCustomers,
      numberOfInvoices,
      totalPaidInvoices,
      totalPendingInvoices,
    };
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch card data.');
  }
}

const ITEMS_PER_PAGE = 6;
export async function fetchFilteredInvoices(
  query: string,
  currentPage: number,
) {
  const offset = (currentPage - 1) * ITEMS_PER_PAGE;

  try {
    const invoices = await client.sql`
      SELECT
        invoices.id,
        invoices.amount,
        invoices.date,
        invoices.status,
        customers.name,
        customers.email,
        customers.image_url
      FROM invoices
      JOIN customers ON invoices.customer_id = customers.id
      WHERE
        customers.name ILIKE ${`%${query}%`} OR
        customers.email ILIKE ${`%${query}%`} OR
        invoices.amount::text ILIKE ${`%${query}%`} OR
        invoices.date::text ILIKE ${`%${query}%`} OR
        invoices.status ILIKE ${`%${query}%`}
      ORDER BY invoices.date DESC
      LIMIT ${ITEMS_PER_PAGE} OFFSET ${offset}
    `;

    return invoices;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch invoices.');
  }
}

export async function fetchInvoicesPages(query: string) {
  try {
    const count = await client.sql`SELECT COUNT(*)
    FROM invoices
    JOIN customers ON invoices.customer_id = customers.id
    WHERE
      customers.name ILIKE ${`%${query}%`} OR
      customers.email ILIKE ${`%${query}%`} OR
      invoices.amount::text ILIKE ${`%${query}%`} OR
      invoices.date::text ILIKE ${`%${query}%`} OR
      invoices.status ILIKE ${`%${query}%`}
  `;

    const totalPages = Math.ceil(Number(count[0].count) / ITEMS_PER_PAGE);
    return totalPages;
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch total number of invoices.');
  }
}

export async function fetchInvoiceById(id: string) {
  try {
    const data = await client.sql`
      SELECT
        invoices.id,
        invoices.customer_id,
        invoices.amount,
        invoices.status
      FROM invoices
      WHERE invoices.id = ${id};
    `;

    const invoice = data.map((invoice) => ({
      ...invoice,
      // Convert amount from cents to dollars
      amount: invoice.amount / 100,
    }));

    return invoice[0];
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch invoice.');
  }
}

export async function fetchCustomers() {
  try {
    const data = await client.sql`
      SELECT
        id,
        name
      FROM customers
      ORDER BY name ASC
    `;

    const customers = data;
    return customers;
  } catch (err) {
    console.error('Database Error:', err);
    throw new Error('Failed to fetch all customers.');
  }
}

export async function fetchFilteredCustomers(query: string) {
  try {
    const data = await client.sql`
		SELECT
		  customers.id,
		  customers.name,
		  customers.email,
		  customers.image_url,
		  COUNT(invoices.id) AS total_invoices,
		  SUM(CASE WHEN invoices.status = 'pending' THEN invoices.amount ELSE 0 END) AS total_pending,
		  SUM(CASE WHEN invoices.status = 'paid' THEN invoices.amount ELSE 0 END) AS total_paid
		FROM customers
		LEFT JOIN invoices ON customers.id = invoices.customer_id
		WHERE
		  customers.name ILIKE ${`%${query}%`} OR
        customers.email ILIKE ${`%${query}%`}
		GROUP BY customers.id, customers.name, customers.email, customers.image_url
		ORDER BY customers.name ASC
	  `;

    const customers = data.map((customer) => ({
      ...customer,
      total_pending: formatCurrency(customer.total_pending),
      total_paid: formatCurrency(customer.total_paid),
    }));

    return customers;
  } catch (err) {
    console.error('Database Error:', err);
    throw new Error('Failed to fetch customer table.');
  }
}
`

**Comment by aaryandewan** [comment]
Ok to anyone suffering from the same problem, this is what you need to do: 

1) Make sure that you have uncommented out the seed/route.ts file
2) You need to deploy your project on vercel.com
3) Go to this url in your browser (whatever your deployed app's URL is obviously not this exact URL)
![image](https://github.com/user-attachments/assets/8f0d6c74-d668-4888-9d9f-6f8b64e84537)
4) Go to it's /seed. Do not go to localhost:3000/seed, instead go to "https://next-learn-o9ve.vercel.app/seed" **[GO TO YOUR PROJECT's URL]**

**Comment by orrymr** [comment]
> 2\. deploy your project on verc

The docs clearly state:

```
Ensure your local development server is running with pnpm run dev and navigate to [localhost:3000/seed](http://localhost:3000/seed) in your browser. When finished, you will see a message "Database seeded successfully" in the browser. Once completed, you can delete this file.
```

As in, do it locally. Yet, this doesn't work. I also had to deploy in order to seed.

**Comment by ok2fly** [comment]
By the way，i have to access github or vercel by a vpn using clashx,   I also have the same error when uncomment the code in `seed/route.s` then  running the code locally by follow instruction in the chapter 6， and solve the error by doing the following:
1.  push the code to github
2. wait for vercel finishing deploy, and visit `https://nextjs-dashboard-omega-pied-21.vercel.app/seed` 
3. turn on vpn and paste and run `export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890  interminal all_proxy=socks5://127.0.0.1:7890`
4. vist 'http://127.0.0.1:3000/seed' then found the error gone, everything is ok
5.

**Comment by riadraz** [comment]
> Ok to anyone suffering from the same problem, this is what you need to do:
> 
> 1. Make sure that you have uncommented out the seed/route.ts file
> 2. You need to deploy your project on vercel.com
> 3. Go to this url in your browser (whatever your deployed app's URL is obviously not this exact URL)
>    ![image](https://private-user-images.githubusercontent.com/49852384/368907425-8f0d6c74-d668-4888-9d9f-6f8b64e84537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjA1OTAsIm5iZiI6MTczMDIyMDI5MCwicGF0aCI6Ii80OTg1MjM4NC8zNjg5MDc0MjUtOGYwZDZjNzQtZDY2OC00ODg4LTlkOWYtNmY4YjY0ZTg0NTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE2NDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNGZhMmI0YmZjYTViNzZjMzEyYjRiMzlhOWQ4NDUxNzc3MzllNTQ1ZTU5ZTEyYmY5ODkxOGNhMDM1NzYwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pt50LMeg3iEVPuDWMQAb3mrw5c3CvkUM5Q8XcwJdsVE)
> 4. Go to it's /seed. Do not go to localhost:3000/seed, instead go to "https://next-learn-o9ve.vercel.app/seed" **[GO TO YOUR PROJECT's URL]**

Thank you , its work for me...

**Comment by trucuit** [comment]
I've tried connect VPN(1111) and it works for me in localhost

**Comment by juniorcreator** [comment]
in vercel there is no Postgres database as in tutorial, could someone help with other database?

**Comment by MarcelDWill** [comment]
heres how i got the queries to work

import postgres from 'postgres';
import { NextResponse } from 'next/server';

// Establish database connection
const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

// Handle GET requests
export async function GET() {
  try {
    const data = await sql`
      SELECT invoices.amount, customers.name
      FROM invoices
      JOIN customers ON invoices.customer_id = customers.id
      WHERE invoices.amount = 666;
    `;

    // Return the data as a JSON response
    return NextResponse.json(data);
  } catch (error) {
    console.error('Error fetching invoices:', error);
    return NextResponse.json({ error: 'Failed to fetch invoices' }, { status: 500 });
  }
}

**Comment by 018798** [comment]
Hi All, When I deploy my project from Git to Vercel it fails to deploy. When i remove the route.ts file from Seed folder it successfully deploys but when i leave it in from the downloaded project it fails. Any help here would be appreciated.

**Comment by sbInfin1** [comment]
@aidinio thanks for the solution. But it is not working for me to be honest. I visited the endpoint which triggered the scripts. I left it for 40 mins. It was still executing. I stopped my server after that.

**Comment by chen-luke** [comment]
> [@aidinio](https://github.com/aidinio) thanks for the solution. But it is not working for me to be honest. I visited the endpoint which triggered the scripts. I left it for 40 mins. It was still executing. I stopped my server after that.

I am having the same issue. I can seed the database locally but it runs forever. Then when I try to drop the tables in postgres to try again it hangs forever as well. If I use the vercel-deploy/seed link I get connection error -111??? At this point I am just going to manually create some of these tables in postgres.

**Comment by katiehartrick** [comment]
> Can you tell me where to put route.ts? I do not have that file although i followed the tutorial the best i could but do not have more background knowledge. So it looks like this tutorial is tightly coupled to forced usage of online service (although the free plan is enough) so you cant progress / finish the course without them.

@sbaum2s `route.ts` is located in `app/seed/route.ts`

**Comment by sbaum2s** [comment]
> No need to change anything anywhere. I have followed the all the things mentioned. Just open the database here and see if you can see the tables and data within. In my case I forget to remove first return as suggested in message itself.
> 
> <img alt="Image" width="809" height="311" src="https://private-user-images.githubusercontent.com/208109388/497068555-a4b54399-2cbb-45d1-8355-a6bd9a37ede8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk0ODg1NDYsIm5iZiI6MTc1OTQ4ODI0NiwicGF0aCI6Ii8yMDgxMDkzODgvNDk3MDY4NTU1LWE0YjU0Mzk5LTJjYmItNDVkMS04MzU1LWE2YmQ5YTM3ZWRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwM1QxMDQ0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDU2ZDc4ODA4YzQyMmExZDI3Yzk0ZDU3YjMzZTE5OTQ1ZDJlMzYwOTA2YWRjOGQ2ZTExNjRiZmRhYTY5NjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TlIWpW69HZ2ULgu0vNX1AMf95NZpgCZPLoAbBGsHLbU"> <img alt="Image" width="1541" height="606" src="https://private-user-images.githubusercontent.com/208109388/497068173-3ca18aa3-0527-4703-8afd-623f0948bb4d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk0ODg1NDYsIm5iZiI6MTc1OTQ4ODI0NiwicGF0aCI6Ii8yMDgxMDkzODgvNDk3MDY4MTczLTNjYTE4YWEzLTA1MjctNDcwMy04YWZkLTYyM2YwOTQ4YmI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwM1QxMDQ0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzU5OTU3N2Y0NzYxYzM0OTRlOTg2Y2U5MDk4N2YwMjc4Y2I3OGU1ZjY2ZTgxODc5Yzc4NDIyNjFiMThjZmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3dvZFeSUpSgvoEQYcUk-rAV-c0Fi2aosN2Ba9zd7Fbs">

For me the tutorial is difficult to follow. and inconsistent its disencouraging. Since opinions of starters do not really count here i´m out and just go a different path.
