### ISSUE TITLE
Trouble with first install of tutorial

### ISSUE THREAD

**Issue by guice** [vercel/next-learn#83]
It says to report this, so I'm doing so:
```
Downloading files from repo https://github.com/vercel/next-learn/tree/master/basics/learn-starter. This might take a moment.

? Could not download "https://github.com/vercel/next-learn/tree/master/basics/learn-starter" because of a connectivity issue between your machine and GitHub.
✔ Could not download "https://github.com/vercel/next-learn/tree/master/basics/learn-starter" because of a connectivity issue between your machine and GitHub.
Do you want to use the default template instead? … no

Aborting installation.
Unexpected error. Please report it as a bug:
 DownloadError: Premature close
    at createApp (/Users/pz/.npm/_npx/efeac22998af9bf2/node_modules/create-next-app/dist/index.js:317:17028)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Users/pz/.npm/_npx/efeac22998af9bf2/node_modules/create-next-app/dist/index.js:317:23064)

➜  Projects npm -v                                                                                                                     
8.13.2
➜  Projects node -v
v18.6.0
```

I'm too new at NextJS to know what's happening here and what to do to fix it. Today's my only day to really sit down with this, so hopefully the default template route will assist.

**Comment by guice** [comment]
It does appear to be working now. Must have been a problem that whole day as I tried several times before filing the report.

```
➜  Downloads $ npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
Creating a new Next.js app in /Users/pz/Downloads/nextjs-blog.

Downloading files from repo https://github.com/vercel/next-learn/tree/master/basics/learn-starter. This might take a moment.

Installing packages. This might take a couple of minutes.


added 18 packages, and audited 19 packages in 6s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Initialized a git repository.

Success! Created nextjs-blog at /Users/pz/Downloads/nextjs-blog
Inside that directory, you can run several commands:

  npm run dev
    Starts the development server.

  npm run build
    Builds the app for production.

  npm start
    Runs the built app in production mode.

We suggest that you begin by typing:

  cd nextjs-blog
  npm run dev

A new version of `create-next-app` is available!
You can update by running: npm install --global create-next-app
```
