### ISSUE TITLE
pnpm dev -> ELIFECYCLE Command failed with exit code 1

### ISSUE THREAD

**Issue by Genshie** [vercel/next-learn#866]
I just started the project now, I'm on windows and when run `pnpm dev` after `pnpm i`,
I get this console message : 
D:\**\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-canary.56_react-dom@19.0.0-rc-f38c22b244-20240704_react@19.0.0-rc-f38c22b244-20240704\node_modules\next\dist\compiled\@edge-runtime\primitives\fetch.js.text.js:1

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at mod.require (D:\**\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-canary.56_react-dom@19.0.0-rc-f38c22b244-20240704_react@19.0.0-rc-f38c22b244-20240704\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at load (D:\**\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-canary.56_react-dom@19.0.0-rc-f38c22b244-20240704_react@19.0.0-rc-f38c22b244-20240704\node_modules\next\dist\compiled\@edge-runtime\primitives\load.js:180:17)
    at Object.<anonymous> (D:\**\nextjs-dashboard\node_modules\.pnpm\next@15.0.0-canary.56_react-dom@19.0.0-rc-f38c22b244-20240704_react@19.0.0-rc-f38c22b244-20240704\node_modules\next\dist\compiled\@edge-runtime\primitives\index.js:5:39)

Node.js v20.15.1
 ELIFECYCLE  Command failed with exit code 1. 

Can someone explain me what's wrong, pls ? :/

**Comment by leerob** [comment]
Could you try again please?
